apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: '${APP}-prod'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
      - name: '${APP}'
        image: 'app'
        env:
          - name: 'ENV'
            value: 'Prod'
