apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: '${APP}'
description: 'Deployment pipeline for ${APP}'
serialPipeline:
  stages:
    - targetId: 'stg'
      profiles: ['stg']
    - targetId: 'prod'
      profiles: ['prod']
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'stg'
description: 'Staging target'
run:
  location: 'projects/${PROJECT_ID}/locations/${REGION}'
executionConfigs:
- usages:
  - RENDER
  - PREDEPLOY
  - DEPLOY
  - VERIFY
  - POSTDEPLOY
  serviceAccount: ${RUN_SERVICE_ACCOUNT}
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'prod'
description: 'Production target'
requireApproval: true
run:
  location: 'projects/${PROJECT_ID}/locations/${REGION}'
executionConfigs:
- usages:
  - RENDER
  - PREDEPLOY
  - DEPLOY
  - VERIFY
  - POSTDEPLOY
  serviceAccount: ${RUN_SERVICE_ACCOUNT}
