apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: '${APP}'
deploy:
  cloudrun: {}
profiles:
  - name: 'dev'
    manifests:
      rawYaml:
        - 'app-dev.yaml'
  - name: 'prod'
    manifests:
      rawYaml:
        - 'app-prod.yaml'
